#include <iostream>
#include <algorithm>
#include <sstream>
#include <cctype>
#include <iomanip>
#include <fstream>
#include <vector>
#include <utility>
#include <string>
#include <list>
#include <map>